// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJf_HpQGV87g6ledLGLPE674w2K8NKyVw',
    appId: '1:336662793322:web:d51e6a2505e2e8d3d14e13',
    messagingSenderId: '336662793322',
    projectId: 'mad2maps',
    authDomain: 'mad2maps.firebaseapp.com',
    storageBucket: 'mad2maps.appspot.com',
    measurementId: 'G-0P4LDQKKCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfc5ILf8RLwGNUAn2Et7eQpx-nfSvxxlk',
    appId: '1:336662793322:android:3a85716fc04b564ed14e13',
    messagingSenderId: '336662793322',
    projectId: 'mad2maps',
    storageBucket: 'mad2maps.appspot.com',
  );
}
